name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake devscripts libconfig-dev libevent-dev

    - name: Configure with CMake
      run: cmake -B build -S .

    - name: Build with CMake
      run: cmake --build build

    - name: Package to DEB
      run: |
        mkdir -p debian/DEBIAN
        mkdir -p debian/usr/local/bin
        cp build/obftun debian/usr/local/bin/
        # Copy service and config files
        mkdir -p debian/etc/systemd/system
        cp contrib/obftun.service debian/etc/systemd/system/
        cp contrib/obftun.conf debian/etc/
        # Control file for deb packaging
        cat <<EOF > debian/DEBIAN/control
        Package: obftun
        Version: 1.0
        Section: Network
        Priority: optional
        Architecture: amd64
        Depends: libc6 (>= 2.7)
        Maintainer: psylity <psylity@gmail.com>
        Description: obftun - yet another obfuscated tunnel
        EOF
        dpkg-deb --build debian obftun.deb

    - name: Upload deb package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: obftun.deb
        path: obftun.deb

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload DEB to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: obftun.deb
        asset_name: obftun-${{ github.ref_name }}.deb
        asset_content_type: application/vnd.debian.binary-package
